import type { Recipe } from "./types";

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Bol de quinoa aux légumes rôtis",
    time: "25 min",
    kcal: "480 kcal",
    tags: ["Végétarien", "Sans gluten", "Facile"],
    emoji: "🥗",
    color: "#E8F5E9",
    accent: "#4CAF50",
    desc: "Quinoa, courge butternut, poivrons, tahini citronné",
    description: "Savoureux, coloré et rassasiant — idéal en semaine.",
    portions: 2,
    protein: "18g",
    carbs: "58g",
    fat: "16g",
    ingredients: [
      { qty: "180g", name: "quinoa blanc" },
      { qty: "300g", name: "courge butternut, en cubes" },
      { qty: "2", name: "poivrons (rouge + jaune)" },
      { qty: "1 boîte", name: "pois chiches égouttés" },
      { qty: "3 c. à soupe", name: "tahini" },
      { qty: "1", name: "citron, jus" },
      { qty: "2 c. à soupe", name: "huile d'olive" },
      { qty: "Sel, poivre", name: "au goût" },
    ],
    steps: [
      "Préchauffer le four à 200 °C. Disposer la courge et les poivrons sur une plaque, arroser d'huile, saler. Rôtir 20 min.",
      "Rincer le quinoa. Cuire dans 360 ml d'eau bouillante salée, couvrir et réduire à feu doux 15 min. Retirer du feu, laisser gonfler 5 min.",
      "Mélanger tahini, jus de citron, 2 c. à soupe d'eau et une pincée de sel pour la vinaigrette.",
      "Assembler : quinoa au fond, légumes rôtis, pois chiches. Arroser de vinaigrette tahini.",
    ],
  },
  {
    id: "2",
    name: "Saumon teriyaki au riz jasmin",
    time: "20 min",
    kcal: "560 kcal",
    tags: ["Sans gluten", "Rapide", "Protéines"],
    emoji: "🐟",
    color: "#FFF3E0",
    accent: "#FF9800",
    desc: "Filet de saumon, riz jasmin, brocoli, sauce teriyaki maison",
    description: "Un classique rapide avec une sauce maison en 5 minutes.",
    portions: 2,
    protein: "38g",
    carbs: "52g",
    fat: "14g",
    ingredients: [
      { qty: "2 filets", name: "saumon (150g chacun)" },
      { qty: "200g", name: "riz jasmin" },
      { qty: "200g", name: "brocoli en fleurons" },
      { qty: "3 c. à soupe", name: "sauce soja" },
      { qty: "2 c. à soupe", name: "mirin" },
      { qty: "1 c. à soupe", name: "miel" },
      { qty: "1 gousse", name: "ail émincé" },
      { qty: "Graines de sésame", name: "pour servir" },
    ],
    steps: [
      "Cuire le riz jasmin selon les instructions. Cuire le brocoli à la vapeur 5 min.",
      "Mélanger sauce soja, mirin, miel et ail pour la sauce teriyaki.",
      "Chauffer une poêle à feu vif. Saisir le saumon côté peau 3 min, retourner 2 min.",
      "Ajouter la sauce, enrober le saumon et laisser caraméliser 1 min. Servir sur le riz avec le brocoli.",
    ],
  },
  {
    id: "3",
    name: "Pasta e fagioli",
    time: "35 min",
    kcal: "420 kcal",
    tags: ["Végétarien", "Confort", "Batch cook"],
    emoji: "🍝",
    color: "#FCE4EC",
    accent: "#E91E63",
    desc: "Haricots borlotti, petites pâtes, tomates, romarin",
    description: "Le réconfort italien en un bol — simple, profond, nourrissant.",
    portions: 4,
    protein: "16g",
    carbs: "68g",
    fat: "8g",
    ingredients: [
      { qty: "1 boîte", name: "haricots borlotti" },
      { qty: "200g", name: "ditalini ou petites pâtes" },
      { qty: "400g", name: "tomates concassées" },
      { qty: "1L", name: "bouillon de légumes" },
      { qty: "1", name: "oignon émincé" },
      { qty: "3 gousses", name: "ail" },
      { qty: "1 brin", name: "romarin frais" },
      { qty: "Parmesan râpé", name: "pour servir" },
    ],
    steps: [
      "Faire revenir l'oignon et l'ail dans l'huile d'olive 5 min à feu moyen.",
      "Ajouter romarin, tomates concassées et bouillon. Laisser mijoter 10 min.",
      "Incorporer les haricots. Écraser grossièrement 1/3 avec une fourchette pour épaissir.",
      "Ajouter les pâtes et cuire selon le temps indiqué. Ajuster sel et poivre. Servir avec parmesan.",
    ],
  },
  {
    id: "4",
    name: "Poulet miso aux champignons",
    time: "30 min",
    kcal: "510 kcal",
    tags: ["Sans gluten", "Umami", "Protéines"],
    emoji: "🍗",
    color: "#F3E5F5",
    accent: "#9C27B0",
    desc: "Cuisse de poulet, shiitakes, pâte miso blanche, gingembre",
    description: "Umami profond, cuisson en une seule poêle.",
    portions: 2,
    protein: "42g",
    carbs: "18g",
    fat: "28g",
    ingredients: [
      { qty: "2", name: "cuisses de poulet désossées" },
      { qty: "200g", name: "shiitakes (ou champignons mélangés)" },
      { qty: "2 c. à soupe", name: "pâte miso blanche" },
      { qty: "1 c. à soupe", name: "sauce soja" },
      { qty: "1 c. à café", name: "gingembre frais râpé" },
      { qty: "2 c. à soupe", name: "saké ou vin blanc" },
      { qty: "1 c. à soupe", name: "huile de sésame" },
      { qty: "Ciboulette", name: "pour servir" },
    ],
    steps: [
      "Mélanger miso, sauce soja, gingembre et saké. Badigeonner le poulet et mariner 10 min.",
      "Chauffer l'huile de sésame à feu moyen-vif. Saisir le poulet 6 min côté peau, retourner 4 min. Réserver.",
      "Dans la même poêle, sauter les champignons 5 min jusqu'à dorés.",
      "Remettre le poulet, ajouter 2 c. à soupe d'eau, couvrir 3 min. Servir avec ciboulette.",
    ],
  },
  {
    id: "5",
    name: "Tacos de lentilles épicées",
    time: "25 min",
    kcal: "390 kcal",
    tags: ["Végétalien", "Épicé", "Facile"],
    emoji: "🌮",
    color: "#FFF8E1",
    accent: "#FFC107",
    desc: "Lentilles beluga, avocat, salsa verde, crème de cajou",
    description: "Végétalien, rapide, et franchement meilleur que la version viande.",
    portions: 3,
    protein: "14g",
    carbs: "54g",
    fat: "12g",
    ingredients: [
      { qty: "250g", name: "lentilles beluga cuites" },
      { qty: "6", name: "tortillas de maïs" },
      { qty: "2", name: "avocats mûrs" },
      { qty: "200ml", name: "salsa verde (du commerce)" },
      { qty: "100ml", name: "crème de cajou" },
      { qty: "1 c. à café", name: "cumin" },
      { qty: "1 c. à café", name: "chili en poudre" },
      { qty: "Coriandre fraîche", name: "pour servir" },
    ],
    steps: [
      "Assaisonner les lentilles avec cumin, chili, sel et poivre. Réchauffer à la poêle 5 min.",
      "Écraser les avocats avec jus de citron vert et sel.",
      "Réchauffer les tortillas directement sur la flamme ou à sec 30 sec de chaque côté.",
      "Assembler : guacamole, lentilles, salsa verde, crème de cajou, coriandre.",
    ],
  },
];

export const GENERATION_MESSAGES = [
  "On analyse tes préférences…",
  "Première recette en préparation…",
  "On équilibre les nutriments…",
  "Troisième recette trouvée…",
  "Presque là…",
  "Dernière touche…",
  "Ta semaine est prête ✨",
];
